Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -57,141 +57,143 @@ jobs:
             - "/usr/local/bin/gsutil"
             - "/usr/local/Caskroom/google-cloud-sdk"
           key: "gc-sdk-cache-key"
+      - restore_cache:
+          key: "d"
+      - restore_cache:
+          key: "e"
       - run:
           name: "Install Unity Hub and Unity Editor"
           command: |
-            echo "if not found install it, otherwise skip installation"
-          #  readonly unity_hub_path="/Applications/Unity Hub.app/Contents/MacOS/Unity Hub"
-          #  readonly unity_editor_path="/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/MacOS/Unity"
+            readonly unity_hub_path="/Applications/Unity Hub.app/Contents/MacOS/Unity Hub"
+            readonly unity_editor_path="/Applications/Unity/Hub/Editor/2021.3.1f1/Unity.app/Contents/MacOS/Unity"
             
-          #  printf '%s\n' "export UNITY_HUB_PATH=\"$unity_hub_path\"" >> "$BASH_ENV"
-          #  printf '%s\n' "export UNITY_EDITOR_PATH=$unity_editor_path" >> "$BASH_ENV"
-          #  check_and_install_unity_hub() {
-          #    if [ ! -f "$unity_hub_path" ]; then
-          #      printf '%s\n' "Could not find Unity Hub at \"$unity_hub_path\"."
-          #      printf '%s\n' "Installing it with brew..."
-          #      brew install --cask unity-hub
-          #      if [ -f "$unity_hub_path" ]; then
-          #        printf '%s\n' "Unity Hub installed successfully."
-          #      else
-          #        printf '%s\n' "Could not install the Unity Hub."
-          #        printf '%s\n' "Please try again or open an issue."
-          #        return 1
-          #      fi
-          #    fi
-          #    return 0
-          #  }
-          #  check_and_install_unity_editor() {
-          #    if [ ! -f "$unity_editor_path" ]; then
-          #      printf '%s\n' "Could not find the Unity Editor at \"$unity_editor_path\"."
-          #      printf '%s\n' "Installing it with the Unity Hub..."
-          #      if check_and_install_unity_hub; then
-          #        if ! command -v npm &> /dev/null; then
-          #          printf '%s\n' "npm is required to fetch the Unity Editor changeset."
-          #          printf '%s\n' "Please install it and try again."
-          #          return 1
-          #        fi
-          #        changeset="$(npx unity-changeset "2021.3.1f1")"
-          #        set -x
-          #        export PLATFORM_NAME=$(echo <<parameters.platform>> | tr "[:upper:]" "[:lower:]")
-          #        "$unity_hub_path" -- --headless install --version "2021.3.1f1" --changeset "3b70a0754835" --module mac-il2cpp $PLATFORM_NAME --childModules
-          #        set +x
-          #        if [ -f "$unity_editor_path" ]; then
-          #          printf '%s\n' "Unity Editor installed successfully."
-          #        else
-          #          printf '%s\n' "Could not install the Unity Editor."
-          #          printf '%s\n' "Please try again or open an issue."
-          #          return 1
-          #        fi
-          #      else
-          #        printf '%s\n' "Could not install the Editor because Unity Hub is not installed."
-          #        return 1
-          #      fi
-          #    fi
-          #    return 0
-          #  }
-          #  resolve_unity_serial() {
-          #    if [ -n "$UNITY_USERNAME" ] && [ -n "$UNITY_PASSWORD" ]; then
+            printf '%s\n' "export UNITY_HUB_PATH=\"$unity_hub_path\"" >> "$BASH_ENV"
+            printf '%s\n' "export UNITY_EDITOR_PATH=$unity_editor_path" >> "$BASH_ENV"
+            check_and_install_unity_hub() {
+              if [ ! -f "$unity_hub_path" ]; then
+                printf '%s\n' "Could not find Unity Hub at \"$unity_hub_path\"."
+                printf '%s\n' "Installing it with brew..."
+                brew install --cask unity-hub
+                if [ -f "$unity_hub_path" ]; then
+                  printf '%s\n' "Unity Hub installed successfully."
+                else
+                  printf '%s\n' "Could not install the Unity Hub."
+                  printf '%s\n' "Please try again or open an issue."
+                  return 1
+                fi
+              fi
+              return 0
+            }
+            check_and_install_unity_editor() {
+              if [ ! -f "$unity_editor_path" ]; then
+                printf '%s\n' "Could not find the Unity Editor at \"$unity_editor_path\"."
+                printf '%s\n' "Installing it with the Unity Hub..."
+                if check_and_install_unity_hub; then
+                  if ! command -v npm &> /dev/null; then
+                    printf '%s\n' "npm is required to fetch the Unity Editor changeset."
+                    printf '%s\n' "Please install it and try again."
+                    return 1
+                  fi
+                  changeset="$(npx unity-changeset "2021.3.1f1")"
+                  set -x
+                  "$unity_hub_path" -- --headless install --version "2021.3.1f1" --changeset "3b70a0754835" --module mac-il2cpp ios android --childModules
+                  set +x
+                  if [ -f "$unity_editor_path" ]; then
+                    printf '%s\n' "Unity Editor installed successfully."
+                  else
+                    printf '%s\n' "Could not install the Unity Editor."
+                    printf '%s\n' "Please try again or open an issue."
+                    return 1
+                  fi
+                else
+                  printf '%s\n' "Could not install the Editor because Unity Hub is not installed."
+                  return 1
+                fi
+              fi
+              return 0
+            }
+            resolve_unity_serial() {
+              if [ -n "$UNITY_USERNAME" ] && [ -n "$UNITY_PASSWORD" ]; then
                 # Serial provided.
-          #      if [ -n "$unity_serial" ]; then
-          #        printf '%s\n' "Detected Unity serial."
-          #        readonly resolved_unity_serial="$unity_serial"
+                if [ -n "$unity_serial" ]; then
+                  printf '%s\n' "Detected Unity serial."
+                  readonly resolved_unity_serial="$unity_serial"
                 # License provided.
-          #      elif [ -n "$UNITY_ENCODED_LICENSE" ]; then
-          #        printf '%s\n' "No serial detected. Extracting it from the encoded license."
+                elif [ -n "$UNITY_ENCODED_LICENSE" ]; then
+                  printf '%s\n' "No serial detected. Extracting it from the encoded license."
                   
-          #        if ! extract_serial_from_license; then
-          #          printf '%s\n' "Failed to parse the serial from the Unity license."
-          #          printf '%s\n' "Please try again or open an issue."
-          #          printf '%s\n' "See the docs for more details: https://game.ci/docs/circleci/activation#personal-license"
-          #          return 1
+                  if ! extract_serial_from_license; then
+                    printf '%s\n' "Failed to parse the serial from the Unity license."
+                    printf '%s\n' "Please try again or open an issue."
+                    printf '%s\n' "See the docs for more details: https://game.ci/docs/circleci/activation#personal-license"
+                    return 1
                   
-          #        else
-          #          readonly resolved_unity_serial="$decoded_unity_serial"
-          #          printf '%s\n' "export RESOLVED_UNITY_SERIAL=$resolved_unity_serial" >> "$BASH_ENV"
-          #        fi
+                  else
+                    readonly resolved_unity_serial="$decoded_unity_serial"
+                    printf '%s\n' "export RESOLVED_UNITY_SERIAL=$resolved_unity_serial" >> "$BASH_ENV"
+                  fi
                 # Nothing provided.
-          #      else
-          #        printf '%s\n' "No serial or encoded license found."
-          #        printf '%s\n' "Please run the script again with a serial or encoded license file."
-          #        printf '%s\n' "See the docs for more details: https://game.ci/docs/circleci/activation"
-          #        return 1
-          #      fi
-          #    fi
-          #    return 0
-          #  }
-          #  extract_serial_from_license() {
+                else
+                  printf '%s\n' "No serial or encoded license found."
+                  printf '%s\n' "Please run the script again with a serial or encoded license file."
+                  printf '%s\n' "See the docs for more details: https://game.ci/docs/circleci/activation"
+                  return 1
+                fi
+              fi
+              return 0
+            }
+            extract_serial_from_license() {
               # Fix locale setting in PERL.
               # https://stackoverflow.com/a/7413863
-          #    export LC_CTYPE=en_US.UTF-8
-          #    export LC_ALL=en_US.UTF-8 
-          #    local unity_license
-          #    local developer_data
-          #    local encoded_serial
-          #    unity_license="$(base64 --decode \<<< "$UNITY_ENCODED_LICENSE")"
-          #    developer_data="$(perl -nle 'print $& while m{<DeveloperData Value\="\K.*?(?="/>)}g' \<<< "$unity_license")"
-          #    encoded_serial="$(cut -c 5- \<<< "$developer_data")"
+              export LC_CTYPE=en_US.UTF-8
+              export LC_ALL=en_US.UTF-8 
+              local unity_license
+              local developer_data
+              local encoded_serial
+              unity_license="$(base64 --decode \<<< "$UNITY_ENCODED_LICENSE")"
+              developer_data="$(perl -nle 'print $& while m{<DeveloperData Value\="\K.*?(?="/>)}g' \<<< "$unity_license")"
+              encoded_serial="$(cut -c 5- \<<< "$developer_data")"
               
-          #    decoded_unity_serial="$(base64 --decode \<<< "$encoded_serial")"
-          #    readonly decoded_unity_serial
-          #    if [ -n "$decoded_unity_serial" ]; then return 0; else return 1; fi
-          #  }
+              decoded_unity_serial="$(base64 --decode \<<< "$encoded_serial")"
+              readonly decoded_unity_serial
+              if [ -n "$decoded_unity_serial" ]; then return 0; else return 1; fi
+            }
             # Install the Editor if not already installed.
-          #  if ! check_and_install_unity_editor; then
-          #    printf '%s\n' "Something went wrong."
-          #    printf '%s\n' "Please try again or open an issue."
-          #    exit 1
-          #  fi
+            if ! check_and_install_unity_editor; then
+              printf '%s\n' "Something went wrong."
+              printf '%s\n' "Please try again or open an issue."
+              exit 1
+            fi
             # Check if serial or encoded license was provided.
             # If the latter, extract the serial from the license.
-          #  if ! resolve_unity_serial; then
-          #    printf '%s\n' "Failed to find the serial or parse it from the Unity license."
-          #    printf '%s\n' "Please try again or open an issue."
-          #    exit 1
-          #  fi
+            if ! resolve_unity_serial; then
+              printf '%s\n' "Failed to find the serial or parse it from the Unity license."
+              printf '%s\n' "Please try again or open an issue."
+              exit 1
+            fi
             # If it doesn't exist, create folder for the Unity License File.
-          #  readonly unity_license_file_path="/Library/Application Support/Unity"
-          #  sudo mkdir -p "$unity_license_file_path"
-          #  sudo chmod -R 777 "$unity_license_file_path"
+            readonly unity_license_file_path="/Library/Application Support/Unity"
+            sudo mkdir -p "$unity_license_file_path"
+            sudo chmod -R 777 "$unity_license_file_path"
             # Activate the Unity Editor.
-          #  set -x
-          #  "$unity_editor_path" \
-          #    -batchmode \
-          #    -quit \
-          #    -nographics \
-          #    -username "$UNITY_USERNAME" \
-          #    -password "$UNITY_PASSWORD" \
-          #    -serial "$resolved_unity_serial" \
-          #    -logfile /dev/stdout
-          #  set +x
+            set -x
+            "$unity_editor_path" \
+              -batchmode \
+              -quit \
+              -nographics \
+              -username "$UNITY_USERNAME" \
+              -password "$UNITY_PASSWORD" \
+              -serial "$resolved_unity_serial" \
+              -logfile /dev/stdout
+            set +x
       - save_cache:
           paths:
-            - "Unity Hub installation path"
-          key: "unity-hub-cache-key"
+            - "/Applications/Unity Hub.app"
+          key: "d"
       - save_cache:
           paths:
-            - "Unity Editor installation path"
-          key: "unity-editot-cache-key"
+            - "/Applications/Unity"
+          key: "e"
         
   build-asset-bundles:
     parameters:
@@ -240,8 +242,8 @@ jobs:
       - restore_cache:
           keys: 
             - "gc-sdk-cache-key"
-            - "unity-hub-cache-key"
-            - "unity-editot-cache-key" 
+            - "d"
+            - "e" 
       - run:
           name: "Validate external file name"
           command: |
